version: '2'

services:
  influxdb:
    restart: always
    image: influxdb:1.5
    volumes:
      - "./data/influxdb/:/var/lib/influxdb"
    environment:
      - "INFLUXDB_ADMIN_USER=admin"
      - "INFLUXDB_ADMIN_PASSWORD=password"
      - "INFLUXDB_DB=rspamd"

  rspamd-influx:
    restart: always
    image: quadstingray/rspamd-influxdb:0.5.0
    links:
      - "influxdb:influxdb"
    environment:
      - "RSPAMD_URL=https://your.spam.url"
      - "RSPAMD_PASSWORD=YOUR_PASSWORD"
